# Site settings
title: Mobile First Century
email: contact@mobilefirstcentury.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
exclude: [deploy.sh, gulpfile.js, package.json, README.md, node_modules]

twitter_username: mobilefirstcentury
github_username: mobilefirstcentury

# Build settings
markdown: kramdown   
